server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: dossier_group

services:
  deal:
    url: http://deal:8080/deal

app:
  email:
    base-url: http://localhost:8084
    paths:
      send-documents: /gateway/document/{statementId}/send
      sign-documents: /gateway/document/{statementId}/sign
      confirm-sign: /gateway/document/{statementId}/code