spring:
  application:
    name: dossier
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: il.kornilow@yandex.ru
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enabled: true