spring:
  kafka:
    topics:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      send-ses: send-ses
      credit-issued: credit-issued
      statement-denied: statement-denied
    bootstrap-servers: kafka:9092
    consumer:
      group-id: dossier_group
server:
  port: 8080
services:
  deal:
    url: http://deal:8080/deal
app:
  email:
    base-url: http://localhost:8084
    paths:
      send-documents: /gateway/document/{statementId}/send
      sign-documents: /gateway/document/{statementId}/sign
      confirm-sign: /gateway/document/{statementId}/code